services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=sqlmodel
    ports:
      - "5432:5432"
    # ヘルスチェックを追加: DBが接続可能か確認する
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d sqlmodel"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/sqlmodel
    depends_on:
          db:
            condition: service_healthy # DBがhealthyになるまで待つ

volumes:
  postgres_data: